# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  name: Default

parameters:
  - name: build
    type: boolean
    default: true
  - name: archive
    type: boolean
    default: true
  - name: environment
    type: string
    default: production
    values:    
    - development
    - staging
    - production
variables:
  buildPath : dist
  archiveName: chatreactts
  artifactName: artifactUI
  envFileName: '.env'
  envProdFileName: '.env.production'
stages:
 - stage: LoadENV
   displayName: load environment file
   isSkippable: false
   jobs:
     - job: loadSecureFile
       displayName: load secure file
       steps:
        - task: DownloadSecureFile@1
          displayName: Download .env
          name: DownloadEnv
          inputs:
            secureFile: $(envFileName)
        - task: DownloadSecureFile@1
          displayName: Download .env.production
          name: DownloadEnvProd
          inputs:
            secureFile: $(envProdFileName)   
        - script: |
            echo "Using .env configuration (default) from $(DownloadEnv.secureFilePath)"
            copy "$(DownloadEnv.secureFilePath)" $(envFileName)
            if ${{ parameters.environment }} == "production" (
               echo "Using .env.production configuration from $(DownloadEnvProd.secureFilePath"
               copy "$(DownloadEnvProd.secureFilePath)" $(envProdFileName)
            )
          displayName: 'Select .env file and copy to src'


 - stage: BuilInstallArchive
   displayName: build , install and archive
   isSkippable: true
   dependsOn: [LoadENV]
   jobs:
     - job: build
       displayName: build and install dependency, node if not installed
       condition: eq( ${{ parameters.build }} ,'true')
       steps:
        - task: NodeTool@0
          displayName: 'Install Node.js'
          inputs:
            versionSource: 'spec'
            versionSpec: '22.x'
            retryCountOnDownloadFails: '3'

        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'
          


     - job: archive
       displayName: archive file
       dependsOn: build
       condition: eq( ${{ parameters.archive }} ,'true')
       steps:
        - task: ArchiveFiles@2
          inputs:
            rootFolderOrFile: '$(buildPath)'
            includeRootFolder: true
            archiveType: 'zip'
            archiveFile: '$(Build.ArtifactStagingDirectory)/$(chatreactts).zip'
            replaceExistingArchive: true
        # - task: CopyFiles@2  # Copy built files to staging directory
        #   displayName: 'Copy Built Files to Staging Directory'
        #   inputs:
        #     sourceFolder: 'dist'  # Vite's default output folder. Adjust if you've customized the output directory.
        #     targetFolder: '$(buildArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'artifactUI'
            publishLocation: 'Container'
            MaxArtifactSize: 1000
          
